INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('Breaking Bad','A chemistry teacher becomes a drug kingpin.',12,'Crime, Drama',2008,'/images/tv/breaking-bad.jpg');
INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('Better Call Saul','The rise of lawyer Jimmy McGill.',12,'Crime',2015,'/images/tv/better-call-saul.jpg');
INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('Dark','A mystery unfolds across generations.',12,'Sci-Fi',2017,'/images/tv/dark.jpg');
INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('Stranger Things','Kids face supernatural horrors.',12,'Sci-Fi',2016,'/images/tv/stranger-things.jpg');
INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('Game of Thrones','Noble houses battle for the Iron Throne.',12,'Fantasy',2011,'/images/tv/game-of-thrones.jpg');
INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('House of the Dragon','The Targaryen civil war begins.',12,'Fantasy',2022,'/images/tv/house-of-the-dragon.jpg');
INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('The Last of Us','Joel escorts Ellie across America.',12,'Drama',2023,'/images/tv/the-last-of-us.jpg');
INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('Sherlock','Modern Sherlock Holmes mysteries.',12,'Mystery',2010,'/images/tv/sherlock.jpg');
INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('Peaky Blinders','A gang rises in Birmingham.',12,'Crime',2013,'/images/tv/peaky-blinders.jpg');
INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('The Boys','Corrupt superheroes face vigilantes.',12,'Action',2019,'/images/tv/the-boys.jpg');
INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('Loki','The God of Mischief alters timelines.',12,'Sci-Fi',2021,'/images/tv/loki.jpg');
INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('Daredevil','Blind lawyer fights crime at night.',12,'Action',2015,'/images/tv/daredevil.jpg');
INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('Wednesday','Wednesday Addams solves mysteries.',12,'Fantasy',2022,'/images/tv/wednesday.jpg');
INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('Arcane','Piltover and Zaun descend into conflict.',12,'Animation',2021,'/images/tv/arcane.jpg');
INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('Chernobyl','The nuclear disaster retold.',12,'Drama',2019,'/images/tv/chernobyl.jpg');
INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('Narcos','The rise of Pablo Escobar.',12,'Crime',2015,'/images/tv/narcos.jpg');
INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('The Office','Mockumentary workplace comedy.',12,'Comedy',2005,'/images/tv/the-office.jpg');
INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('Friends','Six friends navigate life in NYC.',12,'Comedy',1994,'/images/tv/friends.jpg');
INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('Attack on Titan Junior High','Comedy spin-off.',12,'Comedy',2015,'/images/tv/aot-junior-high.jpg');
INSERT INTO items (title, description, category_id, genre, release_year, image_url) VALUES ('Mr. Robot','A hacker targets corporations.',12,'Thriller',2015,'/images/tv/mr-robot.jpg');