spring.application.name=peerrank

spring.datasource.url=jdbc:mysql://localhost:3306/peerrank
spring.datasource.username=root
spring.datasource.password=Priyansh@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.web.resources.static-locations=classpath:/static/

tmdb.api.key=a374fb1fe09d4b045ff47471e0bc0901
tmdb.base.url=https://api.themoviedb.org/3

jwt.secret=6bbcc8e44a53d948ff74e5d8e5d8d4c57d94f07fb95a2d4d5f73d5bcab9e41a2
jwt.expiration=${JWT_EXPIRATION:86400000}